#   
#    Evil Tongue v1.1
#       Author: Progr4mm3r
#	    My Website: tolgaozgun.me
#       My GitHub: github.com/tolgaozgun
#		BukkitDev Page: https://dev.bukkit.org/projects/evil-tongue/
#		Spigot Page: https://www.spigotmc.org/resources/evil-tongue.58881
#
#
# Check my other plugin ChestSpawners!
#	    BukkitDev Page: https://dev.bukkit.org/projects/chestspawners
#       Spigot Page: https://www.spigotmc.org/resources/chestspawners.58536/
#    


# Those strings can be changed.
strings:
# Plugin tag
    plugintag: "&6[Evil Tongue]"
    
# This message is sent to everyone but the chosen one
# whenever a new chosen one is selected.
    taggedmessage: "&6A chosen one is selected..."

# This message is only sent to the chosen one
# whenever a new chosen one is selected.
    taggedplayermessage: "&4You are now the chosen one!"

# This message is sent to everyone but the chosen one
# whenever the chosen one has retired.
    untaggedmessage: "&4Chosen one has retired!"

# This message is only sent to the chosen one
# whenever the chosen one has retired.
    untaggedplayermessage: "&4You are no longer the chosen one!"
    
# The hidden string that anyone with permission can type
# to become the new chosen one
    tagmessage: "This is a hidden string"
    
# The hidden string that the chosen one can type
# to retire from being the chosen one.
    untagmessage: "This is another hidden string"

# This message is sent to everyone but to the victim
# whenever the chosen one murders someone.
    deathmessage: "&3%player% &bhas been chosen by the chosen one."

# This message is only sent to the victim
# whenever the chosen one murders someone.
    deathplayermessage: "&3You &bhave been chosen by the chosen one."
    

settings:

    # If set true, checks updates every startup.
    autoupdatecheck: true
    tagaway:
    
    
       # If set true, when the chosen one dies, they retire.
       death: true
       
       # If set true, when the chosen one types the 'untagmessage' set above, they retire.
       untagmessage: true
       
    # If set true, everyone is alerted when the chosen one murders their next victim.   
    deathmessage: true
    
    # Permission to become the chosen one.
    usepermission: "eviltongue.use"
    
    # Permission to reload the plugin.
    reloadpermission: "eviltongue.reload"
    
    # Permission to use the help command for this plugin.
    helppermission: "eviltongue.help"

    
    # Chosen one will be saved below here
    # Don't edit below here.
players:
